// MATLAB Coder
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// zoh_func.hpp
//
// Code generation for function 'zoh_func'
//

#ifndef ADAPTIVE_HEADWAY_DYNAMICCONTROLLER_ZOH_HPP_
#define ADAPTIVE_HEADWAY_DYNAMICCONTROLLER_ZOH_HPP_

// Include files
#include <cmath>

// Function Definitions
void zoh_func(double Ts, double wn, double Ad[9], double Bd[9])
{
  double t13;
  double t14;
  double t15;
  double t17;
  double t18;
  double t2;
  double t20;
  double t23;
  double t24;
  double t25;
  double t7;
  double t8;
  // ZOH_FUNC
  //     [AD,BD] = ZOH_FUNC(TS,WN)
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     29-Apr-2024 14:08:09
  t2 = Ts * wn;
  t7 = t2 * 4.0;
  t8 = std::exp(t2);
  t14 = t2 * t2;
  t13 = 1.0 / t8;
  t15 = t2 * -t2;
  t17 = Ts * Ts * t13 / 2.0;
  t18 = Ts * (t2 + 1.0) * t13;
  t24 = t2 * (wn * wn) * (t2 - 2.0) * t13 / 2.0;
  t25 = t13 * ((t2 * 2.0 + t14) + 2.0) / 2.0;
  t20 = -(t13 * t14 * wn / 2.0);
  t23 = -(Ts * (t2 - 2.0) * t13 / 2.0);
  Ad[0] = t13 * ((-t7 + t14) + 2.0) / 2.0;
  Ad[1] = t2 * ((t2 - 2.0) - 1.0) * t13 * wn;
  Ad[2] = t24;
  Ad[3] = t23;
  Ad[4] = t13 * ((t2 + 1.0) + t15);
  Ad[5] = t20;
  Ad[6] = t17;
  Ad[7] = t18;
  Ad[8] = t25;
  Bd[0] = t13 * (((t7 + t8 * 2.0) + t15) - 2.0) / 2.0;
  Bd[1] = -t2 * ((t2 - 2.0) - 1.0) * t13 * wn;
  Bd[2] = -t24;
  Bd[3] = t23;
  Bd[4] = t13 * ((-t8 + (t2 + 1.0)) + t15);
  Bd[5] = t20;
  Bd[6] = t17;
  Bd[7] = t18;
  Bd[8] = t25 - 1.0;
}

#endif
// End of code generation (zoh_func.hpp)
